name: sm
favicon: null
layout_spectrum: 0.7928149304352701
typography_spectrum: 0.3732807142660022
title: life is a journey.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38001071219332516
  lightness: 0.59073805809021
  saturation: 0.9440795879345387
  rhythmicContrast: 0.8624956987332553
purpose: []
